config/routes.rb
Translate::Application.routes.draw do
  resources :file_upload_attachments

  resources :file_uploads

  resources :sections

  resources :projects

  resources :users

  root 'projects#main'

  post "user/login" => "users#login"
  get "user/test" => "users#test"
  get "signup" => 'welcome#index'

  

end

app/models/file_upload.rb
class FileUpload < ActiveRecord::Base
   has_many :file_upload_attachments
   accepts_nested_attributes_for :file_upload_attachments

   attr_accessible :title
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
  before_action :set_file_upload, only: [:show, :edit, :update, :destroy]

  # GET /file_uploads
  # GET /file_uploads.json
  def index
    @file_uploads = FileUpload.all
  end

  # GET /file_uploads/1
  # GET /file_uploads/1.json
  def show
    @file_upload_attachments = @file_upload.file_upload_attachments.all
  end

  # GET /file_uploads/new
  def new
    @file_upload = FileUpload.new
    @file_upload_attachment = @file_upload.file_upload_attachments.build
  end

  # GET /file_uploads/1/edit
  def edit
  end

  def parse
  end
  handle_asynchronously :parse

  # POST /file_uploads
  # POST /file_uploads.json
  def create
    @file_upload = FileUpload.new(file_upload_params)

    respond_to do |format|
      if @file_upload.save
        params[:file_upload_attachments]['scenario'].each do |s|
          @file_upload_attachment = @file_upload.file_upload_attachments.create!(:scenario => s, :file_upload_id => @file_upload.id)
          Delayed::Job.enqueue ParseJob.new(@file_upload_attachment);
        end
        format.html { redirect_to @file_upload, notice: 'File upload was successfully created.' }
        format.json { render action: 'show', status: :created, location: @file_upload }
      else
        format.html { render action: 'new' }
        format.json { render json: @file_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /file_uploads/1
  # PATCH/PUT /file_uploads/1.json
  def update
    respond_to do |format|
      if @file_upload.update(file_upload_params)
        format.html { redirect_to @file_upload, notice: 'File upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @file_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_uploads/1
  # DELETE /file_uploads/1.json
  def destroy
    @file_upload.destroy
    respond_to do |format|
      format.html { redirect_to file_uploads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_upload
      @file_upload = FileUpload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def file_upload_params
      params.require(:file_upload).permit(:title, file_upload_attachments_attributes: [:id, :file_upload_id, :scenario])
    end
end

app/helpers/file_uploads_helper.rb
module FileUploadsHelper
end

app/views/file_uploads/_form.html.erb
<%= form_for(@file_upload) do |f| %>
  <% if @file_upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@file_upload.errors.count, "error") %> prohibited this file_upload from being saved:</h2>

      <ul>
      <% @file_upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <%= f.fields_for :file_upload_attachments do |p| %>
    <div class="field">
      <%= p.label :scenario %><br>
      <%= p.file_field :scenario, :multiple => true, name: "file_upload_attachments[scenario][]" %>
     </div>
   <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/file_uploads/edit.html.erb
<h1>Editing file_upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @file_upload %> |
<%= link_to 'Back', file_uploads_path %>

app/views/file_uploads/index.html.erb
<h1>Listing file_uploads</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @file_uploads.each do |file_upload| %>
      <tr>
        <td><%= file_upload.title %></td>
        <td><%= link_to 'Show', file_upload %></td>
        <td><%= link_to 'Edit', edit_file_upload_path(file_upload) %></td>
        <td><%= link_to 'Destroy', file_upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New File upload', new_file_upload_path %>

app/views/file_uploads/new.html.erb
<h1>New file_upload</h1>

<%= render 'form' %>

<%= link_to 'Back', file_uploads_path %>

app/views/file_uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @file_upload.title %>
</p>

<% @file_upload_attachments.each do |p| %>
  <%= image_tag p.scenario_url %>
<% end %>

<%= link_to 'Edit', edit_file_upload_path(@file_upload) %> |
<%= link_to 'Back', file_uploads_path %>