config/routes.rb
Translate::Application.routes.draw do
  resources :file_upload_attachments

  resources :file_uploads

  resources :sections

  resources :projects

  resources :users

  root 'projects#main'

  post "user/login" => "users#login"
  get "user/test" => "users#test"
  get "signup" => 'welcome#index'

  

end

app/models/file_upload_attachment.rb
class FileUploadAttachment < ActiveRecord::Base
    mount_uploader :scenario, ScenarioUploader
    belongs_to :file_upload
    attr_accessible :scenario
end

app/controllers/file_upload_attachments_controller.rb
class FileUploadAttachmentsController < ApplicationController
  before_action :set_file_upload_attachment, only: [:show, :edit, :update, :destroy]

  # GET /file_upload_attachments
  # GET /file_upload_attachments.json
  def index
    @file_upload_attachments = FileUploadAttachment.all
  end

  # GET /file_upload_attachments/1
  # GET /file_upload_attachments/1.json
  def show
  end

  # GET /file_upload_attachments/new
  def new
    @file_upload_attachment = FileUploadAttachment.new
  end

  # GET /file_upload_attachments/1/edit
  def edit
  end

  # POST /file_upload_attachments
  # POST /file_upload_attachments.json
  def create
    @file_upload_attachment = FileUploadAttachment.new(file_upload_attachment_params)

    respond_to do |format|
      if @file_upload_attachment.save
        format.html { redirect_to @file_upload_attachment, notice: 'File upload attachment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @file_upload_attachment }
      else
        format.html { render action: 'new' }
        format.json { render json: @file_upload_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /file_upload_attachments/1
  # PATCH/PUT /file_upload_attachments/1.json
  def update
    respond_to do |format|
      if @file_upload_attachment.update(file_upload_attachment_params)
        format.html { redirect_to @file_upload_attachment, notice: 'File upload attachment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @file_upload_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_upload_attachments/1
  # DELETE /file_upload_attachments/1.json
  def destroy
    @file_upload_attachment.destroy
    respond_to do |format|
      format.html { redirect_to file_upload_attachments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_upload_attachment
      @file_upload_attachment = FileUploadAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def file_upload_attachment_params
      params.require(:file_upload_attachment).permit(:file_upload_id, :scenario)
    end
end

app/helpers/file_upload_attachments_helper.rb
module FileUploadAttachmentsHelper
end

app/views/file_upload_attachments/_form.html.erb
<%= form_for(@file_upload_attachment) do |f| %>
  <% if @file_upload_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@file_upload_attachment.errors.count, "error") %> prohibited this file_upload_attachment from being saved:</h2>

      <ul>
      <% @file_upload_attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file_upload_id %><br>
    <%= f.number_field :file_upload_id %>
  </div>
  <div class="field">
    <%= f.label :scenario %><br>
    <%= f.text_field :scenario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/file_upload_attachments/edit.html.erb
<h1>Editing file_upload_attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @file_upload_attachment %> |
<%= link_to 'Back', file_upload_attachments_path %>

app/views/file_upload_attachments/index.html.erb
<h1>Listing file_upload_attachments</h1>

<table>
  <thead>
    <tr>
      <th>File upload</th>
      <th>Scenario</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @file_upload_attachments.each do |file_upload_attachment| %>
      <tr>
        <td><%= file_upload_attachment.file_upload_id %></td>
        <td><%= file_upload_attachment.scenario %></td>
        <td><%= link_to 'Show', file_upload_attachment %></td>
        <td><%= link_to 'Edit', edit_file_upload_attachment_path(file_upload_attachment) %></td>
        <td><%= link_to 'Destroy', file_upload_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New File upload attachment', new_file_upload_attachment_path %>

app/views/file_upload_attachments/new.html.erb
<h1>New file_upload_attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', file_upload_attachments_path %>

app/views/file_upload_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File upload:</strong>
  <%= @file_upload_attachment.file_upload_id %>
</p>

<p>
  <strong>Scenario:</strong>
  <%= @file_upload_attachment.scenario %>
</p>

<%= link_to 'Edit', edit_file_upload_attachment_path(@file_upload_attachment) %> |
<%= link_to 'Back', file_upload_attachments_path %>